name: Publish docs to GitHub Pages

on:
  workflow_call:

permissions:
  contents: write

jobs:
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - uses: MetaMask/action-checkout-and-setup@v3
      - run: yarn build:docs
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
